### ISSUE TITLE
Stock firmware with TMC2100 = Bad Extrusion ratio

### ISSUE THREAD

**Issue by CoyoteProd** [tevo3d/Tevo-Flash#1]
I received my Tevo Flash 29.10.2018
And stock settings of extrusion step/mm are 408
But  when print, all is under extruded....
![photo_2018-11-06_07-30-31](https://user-images.githubusercontent.com/13413101/48046770-f022f680-e195-11e8-8351-a73a42d62bad.jpg)

Good value seems to be between 900 and 1000 step/mm

Do you have idea ??

**Comment by extremeshok** [comment]
Control -> Filament -> E in mm3 , set the diameter to 1.75* depends on the actual diameter of the filament

My Calibrated E-steps was 412

**Comment by CoyoteProd** [comment]
Control -> Filament -> E in mm3 , was OFF.. I have enabled, diameter is 1.75
but...
![photo_2018-11-07_07-15-22](https://user-images.githubusercontent.com/13413101/48113996-971e9580-e25d-11e8-9006-d476c8c0ee77.jpg)

nothing better...

**Comment by CoyoteProd** [comment]
With M92 E1000  (a little bit too high):

![photo_2018-11-07_17-02-04](https://user-images.githubusercontent.com/13413101/48143354-e04b0580-e2ae-11e8-8dc3-1ce0021f19b1.jpg)

**Comment by extremeshok** [comment]
I opened my unit and set each of the drivers to 1.0volts 

they were randomly set between 0.8 and 1.3

My advice is calibrate the extrusion and make sure 100mm = 100mm and set the correct e-steps.

You can set E = mm3 to off, since it made no difference

**Comment by extremeshok** [comment]
guide for setting esteps: https://www.youtube.com/watch?v=Kgy8hVKxtVs

**Comment by CoyoteProd** [comment]
All my drivers are stock setted at 0.95v 
Calibration of EStep/mm is ok.... with a Estep of 960...
But... 
![photo_2018-11-08_08-35-10](https://user-images.githubusercontent.com/13413101/48184100-3eb8c800-e331-11e8-9728-8a0d25c77958.jpg)

**Comment by extremeshok** [comment]
[benchy_gcode.zip](https://github.com/tevo3d/Tevo-Flash/files/2562030/benchy_gcode.zip)
Sliced with simplify3D 4.1 using stock tevo flash profile for both ABS and PLA

Might be your slicer, below is with my ABS gcode
![abs-benchy](https://user-images.githubusercontent.com/5957328/48210228-99791080-e37f-11e8-9c0d-5bfbd25f093c.jpeg)

**Comment by CoyoteProd** [comment]
OK... is defintly my slicer.... Sorry for that... (I'm using Cura....)
Your benchy boat PLA print perfectly with stock EStep of 408

I just switched to simplify3d and all is beautiful....

![photo_2018-11-09_16-22-56](https://user-images.githubusercontent.com/13413101/48271060-c1c64500-e43b-11e8-8d64-618fdb0c512b.jpg)


You can close this issue that is dont relative to printer or firmware at all... and sorry again.....
